# Dataset Overview
The dataset comprises the following features related to the fashion and makeup product supply chain:

* Product Type: The category of the product (e.g., clothing, accessories, makeup).
* SKU: Stock Keeping Unit, a unique identifier for each product.
* Price: The price of the product.
* Availability: The current availability status of the product.
* Number of Products Sold: The number of products sold for a given period.
* Revenue Generated: The total revenue generated from product sales.
* Customer Demographics: Information about the customers, such as age, gender, location, etc.
* Stock Levels: The quantity of each product available in the inventory.
* Lead Times: Time taken for an order to be fulfilled from the supplier's end to the customer's end.
* Order Quantities: The number of products ordered in each transaction.
* Shipping Times: Time taken for shipping products to customers.
* Shipping Carriers: The company responsible for shipping the products.
* Shipping Costs: The cost incurred for shipping each product.
* Supplier Name: The name of the supplier providing the products.
* Location: Location of the supplier.
* Production Volumes: The volume of products manufactured.
* Manufacturing Lead Time: Time taken for the manufacturing process.
* Manufacturing Costs: The cost incurred during the manufacturing process.
* Inspection Results: The results of quality inspection for products.
* Defect Rates: The percentage of defective products.
* Transportation Modes: The modes of transportation used to deliver products.
* Routes: The transportation routes taken for delivery.
* Costs: Various costs associated with the supply chain process.

## ETL (proccess)

In [1]:
# import library
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# read and load Data from Excel file
supply= pd.read_csv("supply_chain_data.CSV",delimiter=";")
supply

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,70,55,802,8662,Non-binary,58,7,96,...,Mumbai,29,215,29,46,Pending,0.2,Road,Route B,188
1,skincare,SKU1,15,95,736,7461,Female,53,30,37,...,Mumbai,23,517,30,34,Pending,4.9,Road,Route B,503
2,haircare,SKU2,11,34,8,9578,Unknown,1,10,88,...,Mumbai,12,971,27,31,Pending,4.6,Air,Route C,142
3,skincare,SKU3,61,68,83,7767,Non-binary,23,13,59,...,Kolkata,24,937,18,36,Fail,4.7,Rail,Route A,255
4,skincare,SKU4,5,26,871,2687,Non-binary,5,3,56,...,Delhi,5,414,3,92,Fail,3.1,Air,Route A,923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,haircare,SKU95,78,65,672,7386,Unknown,15,14,26,...,Mumbai,18,450,26,59,Pending,1.2,Air,Route A,779
96,cosmetics,SKU96,24,29,324,7698,Non-binary,67,2,32,...,Mumbai,28,648,28,18,Pending,3.9,Road,Route A,189
97,haircare,SKU97,4,56,62,4371,Male,46,19,4,...,Mumbai,10,535,13,66,Fail,3.4,Road,Route A,540
98,skincare,SKU98,20,43,913,8526,Female,53,1,27,...,Chennai,28,581,9,6,Pending,2.9,Rail,Route A,882
99,haircare,SKU99,69,17,627,9185,Unknown,55,8,59,...,Chennai,29,921,2,38,Fail,0.3,Rail,Route B,211

In [3]:
supply.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    int64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    int64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    int64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    int64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    int64
dtypes: float64(1), int64(14), object(9)
memory usage: 18.9+ KB

In [4]:
supply.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.00000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.46000,48.400000,460.990000,5776.02000,47.770000,15.960000,49.220000,5.750000,5.550000,17.080000,567.840000,14.77000,47.300000,2.272000,529.240000
std,31.18191,30.743317,303.780074,2732.87984,31.369372,8.785801,26.784429,2.724283,2.713137,8.846251,263.046861,8.91243,28.957126,1.461498,258.284986
min,2.00000,1.000000,8.000000,1062.00000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,104.000000,1.00000,1.000000,0.000000,104.000000
25%,19.75000,22.750000,184.250000,2812.50000,16.750000,8.000000,26.000000,3.750000,3.750000,10.000000,352.000000,7.00000,23.000000,1.000000,319.000000
50%,51.00000,43.500000,392.500000,6006.50000,47.500000,17.000000,52.000000,6.000000,5.000000,18.000000,568.500000,14.00000,46.000000,2.150000,520.000000
75%,77.25000,75.000000,704.250000,8253.75000,73.000000,24.000000,71.250000,8.000000,8.000000,25.000000,797.000000,23.00000,68.500000,3.525000,762.750000
max,99.00000,100.000000,996.000000,9866.00000,100.000000,30.000000,96.000000,10.000000,10.000000,30.000000,985.000000,30.00000,99.000000,4.900000,997.000000

In [5]:
supply.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [6]:
# check object columns
supply["Customer demographics"].value_counts(normalize=True)

Unknown       0.31
Female        0.25
Non-binary    0.23
Male          0.21
Name: Customer demographics, dtype: float64

In [7]:
supply["Customer demographics"].unique()

array(['Non-binary', 'Female', 'Unknown', 'Male'], dtype=object)

In [12]:
supply=supply[supply["Customer demographics"]!="Unknown"]

In [13]:
supply["Customer demographics"].unique()

array(['Non-binary', 'Female', 'Male'], dtype=object)

In [14]:
# check for null values
supply.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [15]:
supply

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,70,55,802,8662,Non-binary,58,7,96,...,Mumbai,29,215,29,46,Pending,0.2,Road,Route B,188
1,skincare,SKU1,15,95,736,7461,Female,53,30,37,...,Mumbai,23,517,30,34,Pending,4.9,Road,Route B,503
3,skincare,SKU3,61,68,83,7767,Non-binary,23,13,59,...,Kolkata,24,937,18,36,Fail,4.7,Rail,Route A,255
4,skincare,SKU4,5,26,871,2687,Non-binary,5,3,56,...,Delhi,5,414,3,92,Fail,3.1,Air,Route A,923
5,haircare,SKU5,2,87,147,2828,Non-binary,90,27,66,...,Bangalore,10,104,17,57,Fail,2.8,Road,Route A,235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,cosmetics,SKU91,62,90,916,1935,Male,98,22,85,...,Delhi,5,207,28,40,Pending,0.6,Rail,Route B,997
92,cosmetics,SKU92,48,44,276,2100,Male,90,25,10,...,Mumbai,4,671,29,63,Pass,0.3,Rail,Route B,230
96,cosmetics,SKU96,24,29,324,7698,Non-binary,67,2,32,...,Mumbai,28,648,28,18,Pending,3.9,Road,Route A,189
97,haircare,SKU97,4,56,62,4371,Male,46,19,4,...,Mumbai,10,535,13,66,Fail,3.4,Road,Route A,540
98,skincare,SKU98,20,43,913,8526,Female,53,1,27,...,Chennai,28,581,9,6,Pending,2.9,Rail,Route A,882

In [16]:
test= pd.read_csv("processed_data.csv")
test

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
3,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
4,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,cosmetics,SKU91,62.111965,90,916,1935.206794,Male,98,22,85,...,Delhi,5,207,28,39.772883,Pending,0.626002,Rail,Route B,996.778315
65,cosmetics,SKU92,47.714233,44,276,2100.129755,Male,90,25,10,...,Mumbai,4,671,29,62.612690,Pass,0.333432,Rail,Route B,230.092783
66,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
67,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
68,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864